const $$=s=>[...document.querySelectorAll(s)],$=s=>document.querySelector(s);
function scrollToId(id){document.getElementById(id)?.scrollIntoView({behavior:"smooth"})}
$$("[data-scroll]").forEach(b=>b.onclick=()=>scrollToId(b.dataset.scroll));
const cards=$$("#gamesGrid article"),tabs=$$(".tabs button"),search=$("#search");let filter="all";
function update(){const q=search.value.toLowerCase();let n=0;cards.forEach(c=>{const ok=(filter==="all"||c.dataset.cat.includes(filter))&&c.dataset.title.toLowerCase().includes(q);c.style.display=ok?"block":"none";if(ok)n++});$("#empty").style.display=n?"none":"block"}
tabs.forEach(b=>b.onclick=()=>{tabs.forEach(x=>x.classList.remove("active"));b.classList.add("active");filter=b.dataset.filter;update()});search.oninput=update;

const section=$("#play"),canvas=$("#game"),start=$("#start"),startTitle=$("#startTitle"),startHint=$("#startHint"),scoreEl=$("#score"),speedHud=$("#hudSpeed"),driftHud=$("#hudDrift"),modeLabel=$("#modeLabel"),surface=$("#surface");
let renderer,scene,camera,car,roadGroup,raf,running=false,speed=0,steer=0,score=0,mode="drift",timer=0;
const keys={};
addEventListener("keydown",e=>{keys[e.key.toLowerCase()]=true;if(["arrowleft","arrowright","arrowup","arrowdown"," "].includes(e.key.toLowerCase()))e.preventDefault()});
addEventListener("keyup",e=>keys[e.key.toLowerCase()]=false);
function mat(color,roughness=.55,metal=.05){return new THREE.MeshStandardMaterial({color,roughness,metalness:metal})}
function box(w,h,d,m){return new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m)}
function makeCar(color=0xd95c3e){const g=new THREE.Group(),body=mat(color,.28,.45),dark=mat(0x202a30,.18,.35),rubber=mat(0x111317,.8,0);const lower=box(2,.42,4.1,body);lower.position.y=.55;g.add(lower);const hood=box(1.75,.22,1.35,body);hood.position.set(0,.82,-1.15);g.add(hood);const cabin=box(1.55,.55,1.9,dark);cabin.position.set(0,1.02,.25);g.add(cabin);const roof=box(1.42,.1,1.65,mat(0x101820,.12,.55));roof.position.set(0,1.33,.25);g.add(roof);const wheelGeo=new THREE.CylinderGeometry(.38,.38,.24,24);for(const x of[-.92,.92])for(const z of[-1.35,1.35]){const w=new THREE.Mesh(wheelGeo,rubber);w.rotation.z=Math.PI/2;w.position.set(x,.4,z);g.add(w)}const light=mat(0xffd99a,.2,.2);for(const x of[-.65,.65]){const l=box(.35,.14,.08,light);l.position.set(x,.69,-2.08);g.add(l)}g.position.y=.05;return g}
function addEnvironment(){scene=new THREE.Scene();scene.background=new THREE.Color(0x9db4c0);scene.fog=new THREE.Fog(0x9db4c0,35,190);camera=new THREE.PerspectiveCamera(62,1,.1,500);camera.position.set(0,4.4,8.5);renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;scene.add(new THREE.HemisphereLight(0xddeeff,0x59645d,2.1));const sun=new THREE.DirectionalLight(0xffffff,3.1);sun.position.set(-35,50,25);sun.castShadow=true;scene.add(sun);const ground=box(220,.25,600,mat(0x68756d,.95,0));ground.position.y=-.25;ground.receiveShadow=true;scene.add(ground);roadGroup=new THREE.Group();scene.add(roadGroup);const asphalt=mat(0x34393d,.92,0),line=mat(0xe5e3d6,.6,0);for(let i=0;i<24;i++){const road=box(10,.08,22,asphalt);road.position.z=-i*22;roadGroup.add(road);const stripe=box(.13,.09,5,line);stripe.position.set(0,.06,-i*22);roadGroup.add(stripe);for(const side of[-1,1]){const edge=box(.12,.1,22,line);edge.position.set(side*4.75,.07,-i*22);roadGroup.add(edge)}}for(let i=0;i<70;i++){const tree=new THREE.Group(),tr=box(.35,2.1,.35,mat(0x604b38));tr.position.y=1.05;tree.add(tr);const crown=new THREE.Mesh(new THREE.ConeGeometry(1.5,3.6,8),mat(0x315b3b));crown.position.y=3.1;tree.add(crown);const side=i%2?-1:1;tree.position.set(side*(13+(i%5)*3),0,-i*10-20);scene.add(tree)}car=makeCar();car.traverse(o=>{if(o.isMesh)o.castShadow=true});scene.add(car)}
function resize(){if(!renderer)return;const r=canvas.getBoundingClientRect(),w=Math.max(320,r.width),h=Math.max(220,r.height);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
function reset(){speed=0;steer=0;score=0;timer=0;car.position.set(0,0,2.5);car.rotation.set(0,0,0);scoreEl.textContent="SCORE 000000";driftHud.textContent="SCORE 0"}
function setupMode(m){mode=m;const names={drift:["3D DRIFT RUN","WASD / ARROWS to drive · SPACE to handbrake","ROAD"],free:["3D FREE DRIVE","WASD / ARROWS to cruise · SPACE to slide","OPEN ROAD"],park:["3D PARK IT","WASD / ARROWS to line up · SPACE to brake","PARKING LOT"],time:["3D TIME ATTACK","WASD / ARROWS to race · beat the clock","CIRCUIT"],traffic:["3D TRAFFIC DODGE","A/D or arrows to change lanes · survive","HIGHWAY"],arcade:["ARCADE CAR GAME","WASD / ARROWS to play","ARCADE"]};const n=names[m]||names.drift;startTitle.textContent=n[0];startHint.textContent=n[1];surface.textContent=n[2];modeLabel.textContent="● LIVE / "+n[0].replace("3D ","")}
function openGame(m){section.style.display="block";setupMode(m);scrollToId("play");start.style.display="flex";if(!renderer){addEnvironment();resize()}reset()}
function run(){running=true;start.style.display="none";cancelAnimationFrame(raf);animate()}
function animate(){if(!running)return;const gas=keys.w||keys.arrowup,brake=keys.s||keys.arrowdown,left=keys.a||keys.arrowleft,right=keys.d||keys.arrowright,hand=keys[" "];speed+=gas?.055:brake?-.11:-.018;speed=Math.max(0,Math.min(1.65,speed));const target=(left?-1:0)+(right?1:0);steer+=(target-steer)*.12;car.position.x+=steer*(.055+speed*.05);car.position.x=Math.max(-3.5,Math.min(3.5,car.position.x));const sideways=Math.abs(steer)*speed;if((hand||mode==="drift")&&speed>.25&&sideways>.08){score+=sideways*22;car.rotation.y+=steer*.025;car.rotation.z=THREE.MathUtils.lerp(car.rotation.z,-steer*.13,.16)}else{car.rotation.y=THREE.MathUtils.lerp(car.rotation.y,-steer*.18,.12);car.rotation.z=THREE.MathUtils.lerp(car.rotation.z,-steer*.06,.12)}roadGroup.position.z=(roadGroup.position.z+speed*1.8)%22;timer+=.016;camera.position.x+=(car.position.x*.48-camera.position.x)*.06;camera.position.y+=(4.3-camera.position.y)*.06;camera.lookAt(car.position.x*.25,1,-8);const kmh=Math.round(speed*125);speedHud.textContent=String(kmh).padStart(3,"0")+" KM/H";scoreEl.textContent=mode==="time"?"TIME "+Math.max(0,30-timer).toFixed(1):"SCORE "+String(Math.round(score)).padStart(6,"0");driftHud.textContent=mode==="drift"?"DRIFT "+Math.round(score):"RUN "+Math.floor(timer);renderer.render(scene,camera);raf=requestAnimationFrame(animate)}
function miniGame(kind){section.style.display="block";setupMode("arcade");const titles={boss:"DRIFT BOSS MINI",rush:"HIGHWAY RUSH",pixel:"PIXEL RALLY",pixelpark:"PIXEL PARKING",drag:"DRAG DASH",pixelgp:"PIXEL GRAND PRIX"};startTitle.textContent=titles[kind]||"ARCADE CAR GAME";startHint.textContent="ARROWS / WASD to play · quick arcade mode";surface.textContent="ARCADE";scrollToId("play");if(!renderer){addEnvironment();resize()}reset();start.style.display="flex"}
$$("[data-game]").forEach(b=>b.onclick=()=>{const m=b.dataset.game;if(["drift","free","park","time","traffic"].includes(m))openGame(m);else miniGame(m)});
$("#startBtn").onclick=run;$("#close").onclick=()=>{running=false;cancelAnimationFrame(raf);section.style.display="none"};$("#random").onclick=()=>{const a=cards.filter(c=>c.style.display!=="none");if(a.length)a[Math.floor(Math.random()*a.length)].querySelector(".play")?.click()};$("#randomRide").onclick=()=>{const r=$$(".rides article");r.forEach(x=>x.classList.remove("selected"));r[Math.floor(Math.random()*r.length)].classList.add("selected")};$$(".rides article").forEach(r=>r.onclick=()=>{$$(".rides article").forEach(x=>x.classList.remove("selected"));r.classList.add("selected")});
$$("#mobileControls button").forEach(b=>{const k=b.dataset.key;b.onpointerdown=e=>{e.preventDefault();keys[k]=true};b.onpointerup=b.onpointercancel=b.onpointerleave=e=>{e.preventDefault();keys[k]=false}});addEventListener("resize",resize);